### ISSUE TITLE
Wrong warning about Erlang version mismatch

### ISSUE THREAD

**Issue by nextl00p** [grisp/rebar3_grisp#14]
During `rebar3 grisp deploy` it will warn about current version beeing not correct although it is:

```===> Current Erlang version ("20") does not match target Erlang version ("20.2"). It is not guaranteed that the deployed release will work!```

From Erlang documentation:
> As from Erlang/OTP 17, the OTP release number corresponds to the major OTP version number. No erlang:system_info() argument gives the exact OTP version

**Comment by eproxus** [comment]
This is an old remnant that should be removed

**Comment by sylane** [comment]
Fixed by https://github.com/grisp/rebar3_grisp/pulls
