### ISSUE TITLE
Start Erlang runtime when source dependencies are included

### ISSUE THREAD

**Issue by Laymer** [grisp/rebar3_grisp#21]
At the moment I am trying to add a specific dependency called [Lasp](https://github.com/lasp-lang/lasp) into a Grisp project by declaring it in the rebar.config deps as follows :
```
{deps, [
  grisp,
  {epmd, {git, "https://github.com/erlang/epmd", {ref, "4d1a59"}}},
  lasp
]}.
```

Unfortunately, this is not enough to make the Lasp library available at runtime. But if the Lasp dependency is declared to be loaded inside the release according to the [Relx specifications](https://github.com/erlware/relx/wiki/Configuration#priority-application-loading) by adding : 

```
{relx, [
    {release, {node , "0.1.0"}, [{epmd, none}, {lasp, load}, node]}
]}.
```

The Erlang runtime is unable to start once deployed to the Grisp board and remains stuck on :

`starting erlang runtime` 

Forever. The same goes if `load` is replaced by `node` or if Lasp is added in the `applications` section inside the `.app.src` file. Currently, the only workaround that has been found is to redeploy the project a second time to the same SD card, but only after removing the source dependency and leaving Lasp only in the `deps` section in the rebar.config file. By doing so the previously added sources are still included but the startup procedure does not get blocked anymore and the Lasp library is available in the shell/application.

Although this workaround is enough to make it possible to use Lasp on Grisp boards, it prevents us from building releases without manually redeploying twice. I'm quite unsure if this is an actual issue or just not the right way to do it, but the confusing part is that when the same project is run using `rebar3 as test shell` command, everything goes just fine, the Erlang runtime remains stuck only when deploying it to a board. 

Any suggestions are welcome :)

**Comment by eproxus** [comment]
Please open this issue in the grisp repository instead since it is related to running software on the board (the release is correctly generated in this case).
