### ISSUE TITLE
OTP is cloned again when changing version

### ISSUE THREAD

**Issue by nextl00p** [grisp/rebar3_grisp#29]
`git fetch` and checking out an other branch should be enough.

**Comment by eproxus** [comment]
There's the `--single-branch` flag:
```
git clone <url> --branch <branch> --single-branch [<folder>]
```

Should be a lot faster.

**Comment by eproxus** [comment]
And also the `--depth` flag: ```
git clone --depth 1
```

See https://stackoverflow.com/questions/1778088/how-to-clone-a-single-branch-in-git

**Comment by nextl00p** [comment]
> There's the --single-branch flag:

We do that already, which means we cannot simply change branches. This is a bit related to #22 

> And also the --depth flag:

Adding it makes sense.

**Comment by eproxus** [comment]
We should have a separate directory for each OTP version already?

**Comment by nextl00p** [comment]
That exlains why it is cloned twice.

**Comment by eproxus** [comment]
I'd consider it a good thing 🙂 Then you could easily hack on it by changing local files.

**Comment by nextl00p** [comment]
```
$ du -sh _grisp/otp/21.0-rc1/build/ _grisp/otp/21.0-rc1/build/.git
566M	_grisp/otp/21.0-rc1/build/
250M	_grisp/otp/21.0-rc1/build/.git
```

It is an overhead of around 250MB per version and project.

**Comment by eproxus** [comment]
Not if `--depth 1` is used:
```
$ g clone gh:grisp/otp --branch grisp/OTP-21.0-rc1 --depth 1 test_clone
$ du -sh test_clone{,/.git}
235M    test_clone
 54M    test_clone/.git
```

**Comment by eproxus** [comment]
Fixed in https://github.com/grisp/grisp_tools/commit/3aba6bf28a411466bcfb4bb44e03417e3e404715
