### ISSUE TITLE
Deploy fails

### ISSUE THREAD

**Issue by nextl00p** [grisp/rebar3_grisp#43]
Using Rebar 3.10 deploying a release with a a own compiled OTP fails.

For stacktrace see: https://public.ci.stritzinger.com/go/tab/build/detail/grisp-rebar3-grisp-hex-tools-master-otp-21.0/4/build/1/build_grisp_project

**Comment by eproxus** [comment]
Seems the `otp_root` option is missing for some reason.

**Comment by eproxus** [comment]
And if I read the code in `grisp_tools` right it's called `erts`? Not sure how this ever worked...
