### ISSUE TITLE
Files in grisp/grisp_base/*/*.c are ignored in user applications

### ISSUE THREAD

**Issue by nextl00p** [grisp/rebar3_grisp#45]
Drivers, NIFs and sysfiles are only included from the `grisp` dependency, but user-level files within `$USERAPPLICATION/grisp/grisp_base/drivers/test_drv.c` are not included for build in the patches and copied into OTP build directory.

**Comment by peerst** [comment]
I’m pretty sure we had this working at some point.  Maybe I’m mistaken or its a regression

**Comment by eproxus** [comment]
It's a regression.
