### ISSUE TITLE
Make deploy destination available via command-line flag

### ISSUE THREAD

**Issue by nextl00p** [grisp/rebar3_grisp#5]

**Comment by nextl00p** [comment]
I think this is solved? @eproxus

**Comment by eproxus** [comment]
I think only for creating the initial project, not for the `rebar3 grisp deploy` task itself...

**Comment by eproxus** [comment]
Wait, it's solved yeah 😄

**Comment by eproxus** [comment]
For the record, the flag is `-d` or `--destination`
