### ISSUE TITLE
Erlang VM exited when using -internal_epmd and rebar 3.14 

### ISSUE THREAD

**Issue by maehjam** [grisp/rebar3_grisp#62]
When deploying a GRiSP application with rebar 3.14 the OTP patch to add the `-internal_epmd` flag (i.e. https://github.com/grisp/otp/commit/5ebbd6a8f166155e32baf64cd68ee781c88e4e83) gets lost in the build process. 

When starting GRiSP using internal epmd (e.g. when having wifi configurations as described in the [wiki](https://github.com/grisp/grisp/wiki/Connecting-over-WiFI)) it results in

```
Protocol 'inet_tcp': register/listen error: econnrefused
Erlang VM exited
```

**Comment by maehjam** [comment]
This might be a bug in with the `system_libs` flag in relx 4.0.0 see https://github.com/erlware/relx/issues/823

**Comment by peerst** [comment]
Out now: rebar 3.14.2

Is this maybe fixed there?  The issue above is close now and its supposed to be fixed here:

https://github.com/erlware/relx/pull/834

So first we need to figure out if this is part of 3.14.2 and if yes figure out that we can fix our problem with this version (possibly not breaking 3.13.x and before if possible)

**Comment by maehjam** [comment]
Not fixed, but with rebar 3.14.2 we now get the error already when we try to deploy the GRiSP application:

```
$ rebar3 grisp deploy -n robot -v 0.1.0
===> Verifying dependencies...
===> Analyzing applications...
===> Compiling robot
* Downloading pre-built OTP package (bb415d58)
* Cached file is up to date
===> Application needed for release not found: kernel
```

**Comment by joaohf** [comment]
Hello,

Seems that we have the same issue as described here: https://github.com/erlang/rebar3/issues/2496

**Comment by eproxus** [comment]
Pretty sure this is not an issue in later versions of Rebar (3.16+?) and rebar3_grisp. Closing for now.
