### ISSUE TITLE
Implement `rebar3 grisp deploy` without the need for -n and -v arguments

### ISSUE THREAD

**Issue by peerst** [grisp/rebar3_grisp#64]
Starting with rebar 3.14 the functionality to figure out what releases are to build is hoisted from relx into rebar3:

https://github.com/erlang/rebar3/blob/master/src/rebar_relx.erl#L114-L153

Saving this from Slack so it doesn't get lost until this is tackled:

MononcQC on #rebar3 slack:  

> If you want to experiment a bit with it and open up the sort of scope you need I don't think we'd oppose it. Would have to check with Tristan for the sort of durability we'd like on that call but I'm assuming this is nicer now than before anyway.
> 
> If the module/call doesn't exist, then you know you're stuck on an old rebar3

**Comment by eproxus** [comment]
Some improvements in ce90e032caba1a5216bb8c22b695ece950641095.

**Comment by eproxus** [comment]
I re-implemented the Rebar logic since it is only picking the highest version of a release if the name is specified. If no name is specified, we anyway behave the same way by erroring out if there are multiple releases.
