### ISSUE TITLE
Unrepeatable fetching of pre-built OTP package 

### ISSUE THREAD

**Issue by ziopio** [grisp/rebar3_grisp#69]
Following the grisp guide...
Running `rebar3 grisp deploy` the first time generates "_grisp" directory with a selected binary package.
For example "_grisp/grisp2/otp/23.3.4.11"

The problem is that this unpacking event is cached somewhere globally in the system.

Generating a new project and running a deploy will fail by giving this output.

> rebar3 grisp deploy
===> Verifying dependencies...
===> Analyzing applications...
===> Compiling grisp_demo
>\* Resolving OTP version
    23.3.4.11 (requirement was "23")
>\* Downloading pre-built OTP package (a80bccc4)
    (file cached)
>\* Extracting package
    (already extracted)
===> Config value for system_libs must be a boolean or directory but found: "c:/Users/Luca Succi/Desktop/grisp_demo/_grisp/grisp/otp/23.3.4.11/install/lib"

The project is missing the searched directory. Currently the workaround is to copy the "_grisp" directory from the first project which succeeded to the one i want to deploy. This issue has been reported both for Windows and Linux systems.

**Comment by GalaxyGorilla** [comment]
Something is screwed up with the caching, downloaded pre-build OTP versions are not extracted into your build folder. You can temporarily fix this by deleting the cache `filename:basedir(user_cache, "grisp").` to enforce downloading the OTP packages again.

**Comment by GalaxyGorilla** [comment]
Fixed by v2.2.2.
